//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace glomix.console.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("glomix.console.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mp3.
        /// </summary>
        internal static string DirectoryMp3 {
            get {
                return ResourceManager.GetString("DirectoryMp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://globaldjmix.com.
        /// </summary>
        internal static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1.
        /// </summary>
        internal static string KeyMenu {
            get {
                return ResourceManager.GetString("KeyMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &lt;F1&gt; for return to MENU
        ///Select number of mix, whan you want delete or [del] if delete all..
        /// </summary>
        internal static string MsgManage {
            get {
                return ResourceManager.GetString("MsgManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select menu or run other operations:
        ///&lt;F2&gt; - Play
        ///&lt;F3&gt; - Managing.
        /// </summary>
        internal static string MsgMenu {
            get {
                return ResourceManager.GetString("MsgMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select item or press &lt;F1&gt; to return in main menu.
        /// </summary>
        internal static string MsgPage {
            get {
                return ResourceManager.GetString("MsgPage", resourceCulture);
            }
        }
    }
}
